# Generated by Django 5.1.2 on 2024-10-26 15:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WM_pp', '0003_images_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.CharField(choices=[('30 TO 70', '30 To 70'), ('70 TO 100', '70 To 100'), ('100 TO 500', '100 TO 500'), ('500 TO 700', '500 TO 700'), ('700 TO 1000', '700 TO 1000'), ('1000 TO 1200', '1000 TO 1200'), ('1200 TO 2000', '1200 TO 2000'), ('2000 TO 2500', '2000 TO 2500')], max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='information',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
