# Generated by Django 5.1.2 on 2024-10-27 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WM_pp', '0007_order_paid_order_payment_id_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WM_pp.order'),
        ),
    ]
